volumes:
    postgres-data:
        external: true
    pg-admin:
        external: true
services:
    postgres:
        build:
            context: ./relational-data
            dockerfile: ./Dockerfile.dev
        volumes:
            - postgres-data:/var/lib/postgresql/data
        environment:
            POSTGRES_MULTIPLE_DATABASES: db
            POSTGRES_PASSWORD: admin
            POSTGRES_USER: admin
        ports:
            - 15432:5432
    pg-admin:
        image: dpage/pgadmin4
        volumes:
            - pg-admin:/var/lib/pgadmin
        ports:
            - 8082:80
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: admin
            PGADMIN_DISABLE_POSTFIX: 1
    ghi:
        image: node:lts-bullseye
        command: /bin/bash run.sh
        working_dir: /app
        volumes:
            - ./ghi:/app
        ports:
            - "3000:3000"
        environment:
            HOST_OS: ${OS}
            NODE_ENV: development
            HOST: "0.0.0.0"
            REACT_APP_FAST_API: http://localhost:8000
            FAST_API_HOST_NAME: http://localhost:8000
    api:
        build:
            context: ./api
            dockerfile: ./Dockerfile.dev
        ports:
            - "8000:8000"
        volumes:
            - ./api:/app
        environment:
            SIGNING_KEY: 87fe4a3fcfb60092dbaeb854a196bc3d9b190aed7930c734749e85245de698420c25f8e6899c421b4494e99459e01058de5daa9d49584cd62ec975da9aea33da
            DATABASE_URL: postgresql://admin:admin@postgres/db
            WAIT_HOSTS: postgres:5432